const carros = [
  {
    id: 1,
    nome: "Honda Civic",
    preco: "R$ 89.900",
    ano: "2023",
    quilometragem: "15.000 km",
    combustivel: "Flex",
    transmissao: "Automático",
    imagem: "/civic.png",
  },
  {
    id: 2,
    nome: "Toyota Corolla",
    preco: "R$ 95.500",
    ano: "2024",
    quilometragem: "8.500 km",
    combustivel: "Híbrido",
    transmissao: "CVT",
    imagem: "/corolla.png",
  },
  {
    id: 3,
    nome: "Volkswagen Jetta",
    preco: "R$ 78.900",
    ano: "2022",
    quilometragem: "22.000 km",
    combustivel: "Flex",
    transmissao: "Automático",
    imagem: "/jetta.png",
  },
  {
    id: 4,
    nome: "Hyundai HB20",
    preco: "R$ 65.900",
    ano: "2023",
    quilometragem: "12.000 km",
    combustivel: "Flex",
    transmissao: "Manual",
    imagem: "/hb20.png",
  },
  {
    id: 5,
    nome: "Chevrolet Onix",
    preco: "R$ 72.500",
    ano: "2024",
    quilometragem: "5.000 km",
    combustivel: "Flex",
    transmissao: "Automático",
    imagem: "/onix.png",
  },
  {
    id: 6,
    nome: "Ford EcoSport",
    preco: "R$ 85.900",
    ano: "2023",
    quilometragem: "18.000 km",
    combustivel: "Flex",
    transmissao: "Automático",
    imagem: "/ecosport.png",
  },
];

module.exports = carros;
